name: Flutter CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - turk/ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: kat/flutterbeep

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Verify Java version
        run: java -version

      - name: Install Flutter SDK
        run: |
          echo "Downloading Flutter SDK..."
          git clone https://github.com/flutter/flutter.git -b stable --depth 1 $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
          export PATH="$HOME/flutter/bin:$PATH"

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses

      - name: Install GTK 3.0 development libraries (if needed)
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev

      - name: Verify Flutter installation
        run: flutter doctor

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        working-directory: app
        run: flutter pub get

      - name: Run Flutter tests
        working-directory: app
        run: flutter test

      - name: Build APK
        working-directory: app
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: app/build/app/outputs/flutter-apk/app-release.apk

      - name: Build iOS (if applicable)
        if: runner.os == 'macOS'
        working-directory: app
        run: flutter build ios --release

      - name: Upload iOS artifact (if applicable)
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa

          #note: this is just to have a change to save.